language: objective-c
osx_image: xcode8.2
os: osx
rvm:
  - 2.0

before_install:
  - gem install xcpretty
  - pod update
  - pod install

script:
  - xcodebuild -version -showsdks
  - set -o pipefail && xcodebuild -workspace "TOTP.xcworkspace" -scheme "TOTP" -destination "platform=iOS Simulator,OS=10.2,name=iPhone 7 Plus" -sdk "iphonesimulator10.2"  -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: UdQT7LK2lKRjz0tbgU0K9x/HJSTseQ1yzBMEiEhbkTTxh/jDl5s7XcruBQOAdB+F2zThhJizdlV1ppoCS76JNnwnzhuX8FBSiA18t3HcyMrp9v/ctQ/Y7V8JVFME4Ngzmp7gmklgy40p+oLTE4CwLO2ZV+1WJWr/HdfSpMiI4LG2CI+PGhBjjgARkmMNgtrZfpW/+L9P/NlZ8ymZkGWcjVadh8/BN3wp1PvhNNrJ+aBSu05Jv+UanvjfTKlmH3d/rqJqidHzZF3n+NUgFaMNAKS2siGlG+zQUcQ1X0+VtObj1S6a1B8KMss9yKQwia85DV5pJ7qxIUBtQqqDd/LIAhRmwF5UYx76/Gh+73WEAbC4TWYQf0zK6L+ASzUROIfj9O0J1ouyBP7UNYfiX8VlEFD+A0giKw2m4bl4VVLGcd9mka0QU5CKgplw4fHjzrGcKilzX2f+COzdoOYfutq6IDpD6A9KLeSjlmt4tduEZAZMm8Vm8r5uu7Q0hGumNJ6zMoROaJpi9CuU3Trt6C2whlXqFZF1NimNDsL23risOnq3CE8MO/XZeRNtTaXy1nco81yrqOqeaPJF2hzPJZvJ650kQC5r6OkzMP0OE3uEN/mX008mLCWyfXTRsEUdhHCY4GiAkaAthidMKvSKrKi05bn3dUT7O3p9ThHFKP1o+7I=
